//tealium universal tag - utag.444 ut4.0.201610261456, Copyright 2016 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={"smartertravel_pageName":"pageName","smartertravel_pageType":"pageType","smartertravel_isLoggedIn":"isLoggedIn","refId":"marketingSource","smartertravel_isKnownUser":"isKnownUser","refClickId":"campaignId","smartertravel_NLSendId":"NLSendId","smartertravel_siteMode":"siteMode"};u.extend=[function(a,b){b.smartertravel_NLSendId=typeof(b['qp.sendId'])=='undefined'?'':b['qp.sendId'];b.smartertravel_siteMode='DESKTOP';b.smartertravel_destinationName=(b.destAirportCode!=''?b.destAirportCode:b.destCityName)
+(b.destStateCode!=''?', '+b.destStateCode:'')+(b.destCountryName!=''?', '+b.destCountryName:(b.destCountryCode!=''?', '+b.destCountryCode:''));b.smartertravel_originName=(b.origAirportCode!=''?b.origAirportCode:b.origCityName)
+(b.origStateCode!=''?', '+b.origStateCode:'')+(b.origCountryCode!=''?', '+b.origCountryCode:'');b.smartertravel_productType=(b.productId==17?'vacation':b.productType);b.smartertravel_currency=b['cp.selcur'];b.smartertravel_isLoggedIn=(typeof(b.signedIn)!='undefined'&&b.signedIn);b.smartertravel_isKnownUser=((b['cp.LogIn']!=undefined&&b['cp.LogIn']!='')||b.smartertravel_isLoggedIn);if(b.pageType=='confirmation')
b.smartertravel_isConversion=b.offerJustSubmittedFlag=='Y';if(b.pageType=='hp'){b.smartertravel_pageName='home';b.smartertravel_pageType='entry';}
else if(b.pageType=='prodhp'){b.smartertravel_pageType='entry';b.smartertravel_pageName=b.productType+".entry";}else{b.smartertravel_pageType=b.pageType;b.smartertravel_pageName=b.productType+"."+b.pageType;if(b['dom.pathname'].indexOf('retailMatrixView.do')>=0)
b.smartertravel_pageName+='.retailMatrixView';else if(b['dom.pathname'].indexOf('retailListView.do')>=0)
b.smartertravel_pageName+='.retailListView';}
if(b.productId==1||b.productId==17){if(b.productId==1){if(b.pageType=='listing')
if(b.tripType=='MD')
b.smartertravel_pageSubtype='multiDestination';else
b.smartertravel_pageSubtype='departing';else if(b.pageType=='returning'){b.smartertravel_pageType='listing';b.smartertravel_pageSubtype='returning';}else
b.smartertravel_pageSubtype='';}
b.smartertravel_flightType=b.tripType=='RT'?'roundtrip':'oneway';switch(b.airCabinClass){case'ECO':b.smartertravel_flightServiceClass='economyCoach';case'PEC':b.smartertravel_flightServiceClass='economyPremium';case'BUS':b.smartertravel_flightServiceClass='business';case'FST':b.smartertravel_flightServiceClass='firstClass';default:b.smartertravel_flightServiceClass='economyCoach';}}else if(b.productId==5){if(document.querySelectorAll('.hotels > .listing'))
b.smartertravel_numResults=document.querySelectorAll('.hotels > .listing').length;if(b.pageType=='detail'&&b.offerMethod=='retail'){try{if(document.getElementById('overViewHeaderPrice'))
b.smartertravel_hotelPrice=document.getElementById('overViewHeaderPrice').innerHTML;var e=document.getElementById("detailsChangeSearchRoomsInput");if(e&&e.options)
b.smartertravel_numRooms=e.options[e.selectedIndex].value;}catch(err){}}}else if(b.productId==8||b.productId==17){switch(b.rentalCarType){case'ECAR':b.smartertravel_carType='economy';case'CCAR':b.smartertravel_carType='compact';case'ICAR':b.smartertravel_carType='mid-size';case'SCAR':b.smartertravel_carType='standard';case'FCAR':b.smartertravel_carType='full-size';case'PCAR':b.smartertravel_carType='premium';case'LCAR':b.smartertravel_carType='luxury';case'STAR':b.smartertravel_carType='convertible';case'IFAR':b.smartertravel_carType='mid-size suv';case'SFAR':b.smartertravel_carType='standard suv';case'MVAR':b.smartertravel_carType='mini van';case'FFAR':b.smartertravel_carType='full-size suv';default:'economy';}}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
window.SmarterTravelData={};for(d in u.data){window.SmarterTravelData[d]=u.data[d];}
}};utag.o[loader].loader.LOAD(id);})("444","pcln.main");}catch(error){utag.DB(error);}
