//tealium universal tag - utag.458 ut4.0.201602021731, Copyright 2016 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){var debug=false;var log=function(message){if(debug)console.log(message);};log("Krux events extension loaded");function waitForKrux(){if(typeof Krux("ns:priceline")==="function"){log("Krux is available to fire events");if(b.pageType=='hp'){fireEvent("KHOEGgC2");attachEventBySelector("button#hotel-btn-submit-retl","click","KHT5p83g");attachEventBySelector("button#air-btn-submit-retl","click","KHT8CbZ2");attachEventBySelector("button#car-btn-submit-retl","click","KHUWG-QH");attachEventBySelector("button#vac-btn-retl","click","KHbvWACB");attachEventBySelector("button#search-btn.search__cruises__cta","click","KHbvr1Xg");attachEventBySelector("a.fancybox.search__hotels__header__badge__link","click","KHbwUTA9",{"NYOP_hp_hotel":true,"NYOP_hp_air":false,"NYOP_hp_car":false});attachEventBySelector("a.search__flights__header__badge__link.fancybox","click","KHbwUTA9",{"NYOP_hp_hotel":false,"NYOP_hp_air":true,"NYOP_hp_car":false});attachEventBySelector("a.search__cars__header__badge__link.fancybox","click","KHbwUTA9",{"NYOP_hp_hotel":false,"NYOP_hp_air":false,"NYOP_hp_car":true});attachEventBySelector("button[href='#sopq-hotels'].button--secondary.fancybox","click","KHb5GWAz");}
if(b.pageType=="confirmation"){if(b.offerJustSubmittedFlag!=undefined&&b.offerJustSubmittedFlag!=null&&b.offerJustSubmittedFlag.toLowerCase()=="y"){if(b.productId==1){if(b.offerMethod=="retail")fireEvent("KHdU72FX");else if(b.offerMethod=="opaque")fireEvent("KJtfEGly");else if(b.offerMethod=="semiopaque")fireEvent("KJtfP8Yu");}
else if(b.productId==5){if(b.offerMethod=="retail")fireEvent("KHdUZ8dZ");else if(b.offerMethod=="opaque")fireEvent("KJtceBEK");else if(b.offerMethod=="semiopaque")fireEvent("KJtcsHXO");}
else if(b.productId==8){if(b.offerMethod=="retail")fireEvent("KHdVWoIk");else if(b.offerMethod=="opaque")fireEvent("KJtgDxE8");else if(b.offerMethod=="semiopaque")fireEvent("'KJtggv-W");}
else if(b.productId==17)fireEvent("KHeGXsRN");else if(b.productId==18)fireEvent("KHeHAmEZ");}}
if(b.pageType=="listing"){if(b.productId==1){if(b.offerMethod=="retail"){attachEventBySelector("div.pricing-info button","click","'KHcsBKgt",{"choose_departure":true,"choose_return":false})}}
if(b.productId==5){if(b.offerMethod=="retail"){fireEvent("KHb8URIr");attachEventBySelector("a.select-hotel.handle-hotel-overview-link-click","click","KHcBgUKh");}
if(b.offerMethod=="semiopaque")fireEvent("KHcBUOFg");}
if(b.productId==8){if(b.offerMethod=="retail"){var checkExist=setInterval(function(){if(document.querySelectorAll("button#reserveItButtonId").length){attachEventBySelector("button#reserveItButtonId","click","KHcjuRli");clearInterval(checkExist);}},100);attachEventBySelector("button.b-grn.b-sq-md","click","KHciBB78");}}
if(b.productId==17){if(b.offerMethod=="retail")attachEventBySelector("div.bt a","click","KHdROcNG");}}
if(b.pageType=="returning"&&b.productId==1&&b.offerMethod=="retail"){attachEventBySelector("div.pricing-info button","click","'KHcsBKgt",{"choose_departure":false,"choose_return":true});}
if(b.pageType=="detail"){if(b.productId==5){attachEventBySelector("button.button-primary.gaHtlEvntTrk-Rates","click","KHcB8jDB");attachEventBySelector("div.reserve > button.button-primary","click","KHcB8jDB");attachEventBySelector("a#detailsChooseRoomButton","click","KHcBuVST");attachEventBySelector("div.choose-now-row > button.button-primary","click","KHcBuVST");}}
if(b.pageType=="startoffer"&&b.offerMethod=="opaque"){if(b.productId==5)fireEvent("KHb85RX6");if(b.productId==1)fireEvent("KHcrNe7-");}
if(b.pageType=="prodhp"){if(b.productId==1){attachEventBySelector("button#air-submit-btn","click","KHcnuKWf");}
if(b.productId==8){attachEventBySelector("button#car-btn-submit-retl","click","KHcYAt8R");}
if(b.productId==17)attachEventBySelector("button#air-submit-btn","click","KHcs5Hca");}}else setTimeout(waitForKrux,50);}
waitForKrux();function fireEvent(kruxEventId,data){log("Krux firing event id ["+kruxEventId+"]");Krux("ns:priceline")("admEvent",kruxEventId,data==undefined?{}:data);}
function attachEventBySelector(selector,event,kruxEventId,data){var elements=document.querySelectorAll(selector);for(var i=0;i<elements.length;i++){log("Krux event attached to "+i+" : "+event+" :"+selector+" : "+kruxEventId);elements[i].addEventListener(event,function(){fireEvent(kruxEventId,data);},true);}}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})("458","pcln.main");}catch(error){utag.DB(error);}
