if(!window.criteo_q||window.criteo_q instanceof Array){var oldQueue=window.criteo_q||[];window.criteo_q=function(){function g(a){for(var b=document.cookie.split(";"),c=0;c<b.length;c++){var f=b[c],e=f.substr(0,f.indexOf("=")).replace(/^\s+|\s+$/g,""),f=f.substr(f.indexOf("=")+1);if(e===a)return(decodeURIComponent||unescape)(f)}return null}function t(a,b){if(a&&1<a.length){"?"===a[0]&&(a="&"+a.substr(1));var c="&"+b+"=",f=a.indexOf(c);if(-1!==f){var e=a.indexOf("&",f+c.length);return a.slice(f+c.length,
0>e?void 0:e)}}}var d={bodyReady:!1,domReady:!1,queue:[],actions:[],disingScheduled:[],accounts:[],acid:null,axid:null,pxsig:null,ccp:null,cop:null},e={tagVersion:"4.4.3",handlerUrlPrefix:("https:"===document.location.protocol?"https://sslwidget.":"http://widget.")+"criteo.com/event",handlerResponseType:"single",responseType:"js",handlerParams:{v:"4.4.3"},extraData:[],customerInfo:[],manualDising:!1,manualFlush:!1,disOnce:!1,partialDis:!1,guidCookieName:"cto_idcpy",guidCookieRetentionTimeHours:9490,
gumSyncFrameEndPoint:"//gum.criteo.com/syncframe",eventMap:{applaunched:"al",viewitem:"vp",viewhome:"vh",viewlist:"vl",viewbasket:"vb",viewsearch:"vs",tracktransaction:"vc",calldising:"dis",setdata:"exd",setemail:"ce"},propMap:{event:"e",account:"a",currency:"c",product:"p",item:"p","item.id":"i","item.price":"pr","item.quantity":"q","product.id":"i","product.price":"pr","product.quantity":"q",data:"d",keywords:"kw",checkin_date:"din",checkout_date:"dout",deduplication:"dd",attribution:"at","attribution.channel":"ac",
"attribution.value":"v",user_segment:"si",new_customer:"nc",customer_id:"ci",email:"m",hash_method:"h",transaction_value:"tv",responseType:"rt"},setters:{seturl:{cfg:"handlerUrlPrefix",evt:"url"},setaccount:{cfg:"account",evt:"account"},setcalltype:{cfg:"handlerResponseType",evt:"type"},setresponsetype:{cfg:"responseType",evt:"type"},oninitialized:{cfg:"onInitialized",evt:"callback"},ondomready:{cfg:"onDOMReady",evt:"callback"},beforeappend:{cfg:"beforeAppend",evt:"callback"},aftereval:{cfg:"afterEval",
evt:"callback"},onflush:{cfg:"onFlush",evt:"callback"}},flags:{disonce:"disOnce",manualdising:"manualDising",manualflush:"manualFlush",nopartialflush:"noPartialFlush",disonpartialflush:"partialDis"}},u=function(a,b,c){var f=new Date;f.setTime(f.getTime()+36E5*c);c="expires="+f.toUTCString();for(var f=document.location.hostname.split("."),e=0;e<f.length;++e){var d=f.slice(f.length-e-1,f.length).join("."),d="domain=."+d;document.cookie=a+"="+(encodeURIComponent||escape)(b)+";"+c+";"+d+";path=/";if((d=
g(a))&&d===b)break}},C=function(){var a=document.createElement("iframe");a.src=e.gumSyncFrameEndPoint;a.setAttribute("style","width:0px; height:0px; border-width:0px; margin:0px; display:none");return a},v=function(a){u(e.guidCookieName,a,e.guidCookieRetentionTimeHours);if(window.localStorage)try{window.localStorage.setItem(e.guidCookieName,a)}catch(b){}},D=function(){var a=C(),b=function(b){b=b.data;if(b.isCriteoMessage)if(b.optout)u(e.guidCookieName,"",0),window.localStorage&&window.localStorage.removeItem(e.guidCookieName);
else if(b.uid&&""!==b.uid)v(b.uid);else{b=g(e.guidCookieName);var f;window.localStorage&&(f=window.localStorage.getItem(e.guidCookieName));var d=b||f;(b&&!f||!b&&f)&&v(d);a.contentWindow.postMessage({uid:d},"*")}};window.addEventListener&&(window.addEventListener("message",b,!1),d.queue.push({event:"appendtag",element:a}))},q=function(a){if(a&&a.referrer){var b=a.createElement("a");b.href=a.referrer;return b}return null};(function(a){var b=g("criteo_acid"),c=g("cto_axid"),f=g("cto_pxsig"),e=g("cto_optout");
null===b&&null===c&&null===e&&null===f?(b=new Date,b.setTime(b.getTime()+1E4),b="expires="+b.toUTCString(),document.cookie=["criteo_write_test=ChUIBBINbXlHb29nbGVSdGJJZBgBIAE","path=/",b].join("; "),b=g("criteo_write_test"),a.canWriteCookie=null!==b,document.cookie="criteo_write_test=; path=/; expires=Thu, 01 Jan 1970 00:00:00 UTC"):(a.acid=b,a.axid=null!==e?"optout":c,a.pxsig=f,a.canWriteCookie=!0)})(d);(function(a,b){var c,f;try{f=a.top.location.search}catch(e){var d=a;try{for(;d.parent.document!==
d.document;)if(d.parent.document)d=d.parent;else break}catch(h){}if(d&&(d=q(d.document)))f=d.search}f&&(c=t(f,"cto_pld"));if(!c)try{var g=q(a.top.document);g&&g.search&&(c=t(g.search,"cto_pld"))}catch(k){}c&&(b.cop=c)})(window,d);(function(a){var b=g("criteo_cookie_perm");null!==b&&(a.ccp=b)})(d);var w=function(){for(var a=0;a<arguments.length;++a)d.queue.push(arguments[a]);r()},r=function(){for(var a=[],b=d.queue,c=0;c<b.length;++c){var f=b[c];if(f instanceof Array)b.splice.apply(b,[c+1,0].concat(f));
else if(f instanceof Function)b.splice(c+1,0,f());else if(f&&"[object Object]"===f.toString())switch(l(f,c,b,a)){case 0:a.push(f);break;case -1:a=a.concat(b.slice(c)),c=b.length}}e.afterEval instanceof Function&&(a=e.afterEval(b,a,d,e));d.queue=a||[];!e.manualFlush&&(!e.noPartialFlush||0===d.queue.length)&&x(0!==d.queue.length)},l=function(a,b,c,f){if(!d.domReady&&a.requiresDOM&&"no"!==a.requiresDOM)return"blocking"===a.requiresDOM?-1:0;delete a.requiresDOM;if(!a.event)return h(a),1;a.account&&s(a.account,
d.accounts);a.event=a.event.toLowerCase();switch(a.event){case "setdata":return a=h(a),e.extraData.push(a),y(d.actions,h(a)),1;case "setparameter":for(var n in a)"event"!==n.toLowerCase()&&a.hasOwnProperty(n)&&(e.handlerParams[n]=a[n]);return 1;case "calldising":a.hasOwnProperty("account")||(a.account=d.accounts);b=e.handlerResponseType;a.hasOwnProperty("type")&&(b=a.type,delete a.type);s(a.account,d.disingScheduled);"sequential"===b&&(a.dc=!0);break;case "setcustomerid":return a.event="setdata",
a.customer_id=a.id,delete a.id,l(a);case "setemail":case "sethashedemail":case "ceh":a.event="setemail";if(a.hasOwnProperty("email")){a.email instanceof Array||(a.email=[a.email]);b=a.email;c=[];for(f=0;f<b.length;f++)void 0!==b[f]&&null!==b[f]&&c.push(String(b[f]));a.email=c}b=h(a);e.customerInfo.push(b);z(d.actions,h(a));return 1;case "setsitetype":b="d";if("mobile"===a.type||"m"===a.type)b="m";if("tablet"===a.type||"t"===a.type)b="t";a.event="setdata";delete a.type;a.site_type=b;return l(a);case "appendtag":d.bodyReady&&
!e.container&&((b=document.body)?(c=document.createElement("div"),c.setAttribute("id","criteo-tags-div"),c.style.display="none",b.appendChild(c),b=c):b=void 0,e.container=b);a.url&&(a.isImgUrl?(b=document.createElement("img"),b.setAttribute("style","display:none;"),b.setAttribute("width","1"),b.setAttribute("height","1")):(b=document.createElement("script"),b.setAttribute("async","true"),b.setAttribute("type","text/javascript")),b.setAttribute("src",a.url),a.element=b);e.beforeAppend instanceof Function&&
(a.element=e.beforeAppend(a.element,d,e));h(a);if(a.element&&(a.element.tagName||a.isImgUrl))if(!e.container&&("script"===a.element.tagName.toLowerCase()||a.isImgUrl))b=document.getElementsByTagName("script")[0],a.element.setAttribute("data-owner","criteo-tag"),b.parentNode.insertBefore(a.element,b);else if(e.container)e.container.appendChild(a.element);else return 0;return 1;case "gettagstate":return a.callback instanceof Function?a.callback(d,e):1;case "flush":case "flushevents":return x(b!==c.length-
1||0!==f.length),1}if(b=e.setters[a.event])return e[b.cfg]=a[b.evt],1;if(b=e.flags[a.event])return e[b]=!0,1;d.actions.push(h(a));return 1},x=function(a){e.onFlush instanceof Function&&(d.actions=e.onFlush(d.actions,d,e));if(0!==d.actions.length){for(var b=0;b<e.extraData.length;++b)y(d.actions,e.extraData[b]);for(b=0;b<e.customerInfo.length;++b)z(d.actions,e.customerInfo[b]);if(!e.manualDising&&(!a||e.partialDis)){a=[];for(b=0;b<d.accounts.length;++b)p(d.disingScheduled,d.accounts[b])||a.push(d.accounts[b]);
0<a.length&&l({event:"callDising",account:a})}b=d.actions;a=[];1===d.accounts.length&&(e.account=d.accounts[0]);e.account&&a.push("a="+k(e.account,[]));"js"!==e.responseType&&a.push("rt="+k(e.responseType,[]));if(e.handlerParams){var c=decodeURIComponent(k(e.handlerParams,[]));c&&a.push(c)}for(c=0;c<b.length;++c)b[c].account&&m(e.account,b[c].account)&&delete b[c].account,a.push("p"+c+"="+k(b[c],[]));null!==d.acid&&a.push("acid="+d.acid);null!==d.axid&&a.push("axid="+d.axid);null!==d.pxsig&&a.push("pxsig="+
d.pxsig);d.canWriteCookie&&a.push("adce=1");null!==d.ccp&&a.push("ccp="+d.ccp);null!==d.cop&&a.push("cop="+d.cop);if(b=g(e.guidCookieName))a.push("idcpy="+b),a.push("iddom="+document.location.hostname);a=a.join("&");a={event:"appendTag",url:e.handlerUrlPrefix+"?"+a,isImgUrl:"gif"===e.responseType};d.actions=[];l(a);e.disOnce||(d.disingScheduled=[])}},y=function(a,b){for(var c=0;c<a.length;++c){var f=a[c];if(f.event===b.event&&m(b.account,f.account)){for(var e in b)b.hasOwnProperty(e)&&"account"!==
e&&(f[e]=b[e]);return}}a.push(b)},z=function(a,b){for(var c=0;c<a.length;++c){var f=a[c];if(f.event===b.event&&m(b.account,f.account)&&("hash_method"in b?b.hash_method:"")===("hash_method"in f?f.hash_method:"")){if(b.hasOwnProperty("email")){for(var c=f,f=f.email,e=b.email,d=[],g=0;g<e.length;++g)p(f,e[g])||d.push(e[g]);f=f.concat(d);c.email=f}return}}a.push(b)},h=function(a){var b=a;if(a instanceof Function)return b=a(),b instanceof Function?b:h(b);if(a instanceof Array)for(var b=[],c=0;c<a.length;++c)b[c]=
h(a[c]);else if(a&&"[object Object]"===a.toString())for(c in b={},a)a.hasOwnProperty(c)&&(b[c]=h(a[c]));return b},F=function(a,b){var c=b.join(".");return e.propMap[c]?e.propMap[c]:a},m=function(a,b){if(!(a instanceof Array))return m([a],b);if(!(b instanceof Array))return m(a,[b]);if(a.length!==b.length)return!1;for(var c=0;c<a.length;++c)if(!p(b,a[c]))return!1;return!0},k=function(a,b){var c="";if(a instanceof Function)c=k(a(),b);else if(a instanceof Array){for(var f=[],d=0;d<a.length;++d)f[d]=k(a[d],
b);c+="["+f.join(",")+"]"}else if(a&&"[object Object]"===a.toString()){f=[];for(d in a)if(a.hasOwnProperty(d)){var g=b.concat([d]);f.push(F(d,g)+"="+k(a[d],g))}c+=f.join("&")}else c=1===b.length&&"event"===b[0]?c+(e.eventMap[a.toLowerCase()]?e.eventMap[a.toLowerCase()]:a):c+a;return encodeURIComponent(c)},s=function(a,b){if(a instanceof Array)for(var c=0;c<a.length;++c)s(a[c],b);else p(b,a)||b.push(a)},p=function(a,b){for(var c=0;c<a.length;++c)if(a[c]===b)return!0;return!1},G=function(a){if(a){var b=
a.createElement("script");b.setAttribute("type","text/javascript");b.setAttribute("src",a.location.protocol+"//static.criteo.net/js/ld/ld-tag-debug.4.4.3.js");a=a.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)}};(function(a){(function c(){document.body?setTimeout(a,0):setTimeout(c,10)})()})(function(){d.bodyReady=e.onInitialized instanceof Function?e.onInitialized(d,e):!0;D();r()});(function(a,b){if("complete"===a.readyState)b();else if(a.addEventListener)a.addEventListener("DOMContentLoaded",
b,!1),window.addEventListener("load",b,!1);else{a.attachEvent("onreadystatechange",b);window.attachEvent("onload",b);var c=!1;try{c=null===window.frameElement&&document.documentElement}catch(e){}if(c&&c.doScroll)(function E(){if(c){try{c.doScroll("left")}catch(a){return setTimeout(E,50)}b()}})();else{var d=!1,g=a.onload,h=a.onreadystatechange;a.onload=a.onreadystatechange=function(){h instanceof Function&&h();if(!d&&(!a.readyState||"loaded"===a.readyState||"complete"===a.readyState))g instanceof Function&&
g(),d=!0,b()}}}})(document,function(){d.domReady=e.onDOMReady instanceof Function?e.onDOMReady(d,e):!0;r()});(function(a){try{var b=q(a);b&&b.hostname!==a.location.hostname&&e.extraData.push({event:"setData",ref:b.protocol+"//"+b.hostname})}catch(c){}})(document);(function(a,b){if(a&&b){var c=/^\#(enable|disable)-criteo-tag-debug-mode(\=(\d+))?$/.exec(b);if(c&&4==c.length){var d="enable"==c[1],e=c[3],c="criteoTagDebugMode=";d&&(e&&!isNaN(e))&&(c+=parseInt(e,10));d=d?(new Date).getTime()+864E5:0;d=
"expires="+(new Date(d)).toUTCString();document.cookie=[c,"path=/",d].join("; ");window.location.href=window.location.href.substr(0,window.location.href.indexOf("#"))}}})(document,window.location.hash);var A;A=document?"function"!=typeof Array.prototype.indexOf?!1:-1!==document.cookie.indexOf("criteoTagDebugMode="):!1;if(A){var B={originalPush:w,stagedPushes:[],stagedErrors:[],push:function(){0<arguments.length&&this.stagedPushes.push(arguments)},pushError:function(a){this.stagedErrors.push(a)}};
window.onerror=function(a){return function(b,c,d,e){B.pushError({message:b,url:c,lineNumber:d,column:e});return a&&"function"===typeof a?a.apply(this,arguments):!1}}(window.onerror);G(document);return B}return{push:w}}();window.criteo_q.push.apply(window.criteo_q,oldQueue)};
